chest_xray_interpretations = ["No acute cardiopulmonary process identified. Heart size within normal limits. Lungs are clear.", "Mild cardiomegaly with no evidence of pulmonary edema. No focal consolidation.", "Right lower lobe consolidation consistent with pneumonia. Heart size normal.", "Small right pneumothorax measuring approximately 1 cm at apex. No tension features.", "Bilateral pleural effusions, right greater than left. Cardiomegaly present.", "Diffuse interstitial changes suggestive of pulmonary fibrosis. No pneumothorax.", 
                              "Left lower lobe atelectasis. Otherwise clear lungs. Normal cardiac silhouette.", "Right upper lobe mass measuring approximately 3.5 cm in diameter. Further evaluation recommended.", "Hyperinflated lungs consistent with COPD. Flattened diaphragms bilaterally.", "Status post median sternotomy with sternal wires intact. No acute findings.", "Right-sided Port-a-Cath with tip at the cavoatrial junction. No pneumothorax.", "Left-sided pleural effusion with compressive atelectasis of the lower lobe.", 
                              "Diffuse bilateral pulmonary nodules, concerning for metastatic disease.", "Right middle lobe infiltrate consistent with aspiration pneumonia.", "Calcified granuloma in the left upper lobe, likely representing prior granulomatous infection.", "Right-sided chest tube in good position with resolution of previously seen pneumothorax.", "Prominent pulmonary vasculature suggestive of pulmonary hypertension.", "Left lower lobe air space opacity consistent with pneumonia. Small pleural effusion.", 
                              "Endotracheal tube positioned approximately 2 cm above the carina.", "Multiple rib fractures on the right side involving ribs 4 through 7."]

abdominal_xray_interpretations = ["Nonspecific bowel gas pattern. No evidence of obstruction or free air.", "Dilated loops of small bowel with air-fluid levels, concerning for small bowel obstruction.", "Moderate amount of stool throughout the colon, suggestive of constipation.", "Enlarged liver shadow extending below the right costal margin.", "Calcifications in the right upper quadrant, likely representing gallstones.", "Multiple surgical clips in the right upper quadrant, consistent with prior cholecystectomy.", 
                                  "Large calcification in the left upper quadrant, likely representing a splenic artery aneurysm.", "Pancreatic calcifications consistent with chronic pancreatitis.", "Renal calculi noted bilaterally, largest measuring approximately 8 mm on the left.", "Retained surgical sponge in the left lower quadrant with characteristic radio-opaque marker.", "Pneumoperitoneum with free air under the right hemidiaphragm.", "Nasogastric tube coiled in the stomach. No evidence of perforation.", 
                                  "Calcified aortic aneurysm measuring approximately 5 cm in diameter.", "Right lower quadrant surgical clips consistent with prior appendectomy.", "Bladder distention with smooth contour. No radio-opaque calculi identified.", "Ileus pattern with dilated loops of bowel and minimal gas in the rectum.", "Fecal loading throughout the colon. No evidence of obstruction.", "Gastric outlet obstruction with distended stomach and minimal distal gas.", "Calcified lymph nodes in the mesentery, likely representing prior granulomatous infection.", 
                                  "Paralytic ileus with diffusely dilated loops of bowel without transition point."]

spinal_xray_interpretations = ["Degenerative disc disease at L4-L5 and L5-S1 with disc space narrowing.", "Grade 1 anterolisthesis of L4 on L5, likely degenerative in nature.", "Compression fracture of T12 vertebral body of indeterminate age.", "Dextroscoliosis of the thoracic spine with Cobb angle measuring approximately 22 degrees.", "Multilevel facet arthropathy in the lumbar spine, most pronounced at L4-L5.", "Posterior fusion hardware from L3 to S1, in good alignment without hardware failure.", 
                               "Cervical spondylosis most prominent at C5-C6 with uncovertebral joint hypertrophy.", "Ankylosis of the sacroiliac joints bilaterally, concerning for ankylosing spondylitis.", "Schmorl's nodes at multiple levels in the thoracic spine.", "Anterior osteophyte formation throughout the lumbar spine, consistent with DISH.", "Loss of cervical lordosis, possibly related to muscle spasm.", "Ossification of the posterior longitudinal ligament at C3-C4 levels.", "Pars defect at L5 bilaterally without spondylolisthesis.", 
                               "Mild levoscoliosis of the lumbar spine with Cobb angle of approximately 12 degrees.", "Anterior wedging of L1 vertebral body, suggesting acute compression fracture.", "Block vertebrae at C2-C3, likely congenital in nature.", "Severe degenerative changes at C5-C6 with marked disc space narrowing.", "Laminectomy defects at L4 and L5 consistent with prior decompression surgery.", "Sacralization of L5 vertebral body with pseudoarticulation on the right.", 
                               "Diffuse idiopathic skeletal hyperostosis (DISH) with flowing ossification along the anterior aspect of the thoracic spine."]

extremity_xray_interpretations = ["Nondisplaced fracture of the right distal radius. No other acute fractures identified.", "Comminuted fracture of the left tibial plateau with mild impaction of the lateral plateau.", "Degenerative changes in the right knee with medial compartment joint space narrowing.", "Avulsion fracture of the right lateral malleolus. No tibial fracture seen.", "Left calcaneal fracture with decreased Böhler's angle, suggesting intra-articular extension.", "Right shoulder dislocation with the humeral head positioned anteriorly and inferiorly.", 
                                  "Degenerative changes at the first carpometacarpal joint consistent with osteoarthritis.", "Fifth metacarpal neck fracture with approximately 30 degrees of angulation.", "Bimalleolar ankle fracture with lateral talar displacement.", "Salter-Harris type II fracture of the distal radial physis.", "Intra-articular distal radius fracture (Smith's fracture) with volar angulation.", "Supracondylar fracture of the right humerus with posterior displacement.", "Left hip joint space narrowing with subchondral sclerosis and osteophyte formation.", 
                                  "Subtle scaphoid waist fracture. Clinical correlation and further imaging recommended.", "Monteggia fracture with proximal ulnar fracture and radial head dislocation.", "Osteopenia throughout visualized bones, most pronounced in the distal radius.", "Bennett fracture of the base of the first metacarpal with subluxation of the carpometacarpal joint.", "Hill-Sachs lesion of the posterolateral humeral head, suggesting prior anterior shoulder dislocation.", "Hip prosthesis in good position without evidence of loosening or periprosthetic fracture.", 
                                  "Lisfranc injury with diastasis between the first and second metatarsal bases."]

pediatric_xray_interpretations = ["Bowel gas pattern consistent with malrotation. Upper GI study recommended.", "Lateral neck film showing submandibular soft tissue swelling consistent with retropharyngeal abscess.", "Buckle fracture of the distal radius, typical of pediatric patients.", "Diffuse increase in bronchovascular markings, consistent with viral pneumonia.", "Bilateral hip dysplasia with shallow acetabular sockets and lateral subluxation.", "Salter-Harris type IV fracture of the distal femur with intra-articular extension.", 
                                  "Supracondylar fracture of the left humerus with mild posterior displacement.", "Classic metaphyseal lesion of the distal femur, concerning for non-accidental trauma.", "Torus fracture of the distal radius without significant angulation or displacement.", "Sunburst periosteal reaction in the proximal tibia, concerning for osteosarcoma."]

miscellaneous_xray_interpretations = ["Right maxillary sinus opacification, consistent with acute sinusitis.", "Mandibular fracture at the angle with mild displacement.", "Foreign body in the left main bronchus, appearing metallic and approximately 2 cm in length.", "Calcified granuloma in the left upper lobe, representing prior granulomatous infection.", "Waters view demonstrating bilateral maxillary sinus opacification.", "Normal elbow fat pads. No evidence of joint effusion.", "Multiple small metallic densities throughout the soft tissues, consistent with shrapnel.", 
                                      "Retained needle fragment in the left gluteal region measuring approximately 1.5 cm.", "Calcified pleural plaques along the lateral chest walls bilaterally, consistent with prior asbestos exposure.", "Erosive changes at the distal interphalangeal joints, suggesting erosive osteoarthritis."]